cleanup code

diff --git a/devtools b/devtools
--- a/devtools
+++ b/devtools
@@ -1,6 +1,11 @@
 #!/bin/bash
-export DEVTOOLS_DIRECTORY="$HOME/.devtools"
 
+set -e
+
+DEVTOOLS_DIRECTORY="$HOME/.devtools"
+EXECUTE_FILE="$DEVTOOLS_DIRECTORY/bin/$1/$2.sh"
+
+# global function
 update_devtools() {
   # update repository
   cd "$DEVTOOLS_DIRECTORY" || exit
@@ -11,48 +16,12 @@ update_devtools() {
   chmod +x "$DEVTOOLS_DIRECTORY/devtools"
 }
 
-install_nginx() {
-  sudo apt-get update
-  sudo apt-get upgrade -y
-  sudo apt-get install -y software-properties-common
-
-  # Nginx
-  sudo apt-get install -y nginx
-
-  # MariaDB
-  sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
-  sudo add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirror2.hs-esslingen.de/mariadb/repo/10.4/ubuntu bionic main'
-
-  sudo add-apt update
-  sudo add-apt install -y mariadb-server
-
-  sudo mysql_secure_installation
-
-  # Php
-  sudo add-apt-repository -y ppa:ondrej/php
-  sudo apt-get update
-
-  sudo add-apt install -y php-fpm php-mysql
-  sudo add-apt install -y php-xml php-mbstring php-curl php-zip php-bcmath
-
-  # Test and reload
-  sudo nginx -t
-  sudo systemctl reload nginx
-}
-
-case ${1} in
-
-'domain')
-  source /opt/devtools/bin/domain/add.sh
-  ;;
-'nginx')
-  install_nginx
-  ;;
-'update')
-  update_devtools
-  ;;
-
-*)
-  echo "Command not found"
-  ;;
-esac
+if [ -f "$EXECUTE_FILE" ]; then
+    # shellcheck disable=SC1090
+    source "$EXECUTE_FILE";
+else
+  echo "devtools: command not found!"
+  echo ""
+  echo "devtools domain add <domain>"
+  echo "devtools setup nginx"
+fi
